sms:
  access-key-id:
  access-key-secret:
  # Endpoint 请参考 https://api.aliyun.com/product/Dysmsapi
  endpoint:
#  signName: 图南
  signName:
  # 一天最大发送次数
  dayMaxTimes: 20
  # 发送频率限制(分钟)
  sendFrequency: 2
  # 验证码有效时间(分钟)
  codeValidTime: 5

face:
  access-key-id:
  access-key-secret:
  endpoint:
