server:
  port: 8080
  tomcat:
    # 当文件超过tomcat的大小限制后会先于Controller触发异常，此时我们的异常处理器无法捕获异常
    max-swallow-size: 100MB # 内嵌tomcat的最大吞吐量，设置 -1 不限制
spring:
  application:
    name: wechat-app
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat_app?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  config:
    import: "classpath:sensitive.properties"

app:
  # 映射路径
  mappingUrl: /profile
  # 文件上传路径
  profile: D:/WorkFromHome/_upload/WechatApp

Wechat:
  AppID: ${wechat.app-id}
  AppSecret: ${wechat.app-secret}

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: top.tolan.**.entity.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 将数据库表的下划线命名方式转换为驼峰命名方式
    map-underscore-to-camel-case: true
  global-config:
    # 是否关闭 MyBatis-Plus 的启动 Banner
    banner: false
